language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - SYMFONY_VERSION=2.7.6
  - SYMFONY_VERSION=2.7.8
  - SYMFONY_VERSION=2.7.9
  - SYMFONY_VERSION=2.8.3

services:
  - mysql
script:
  - phpunit app --coverage-text
matrix:
  allow_failures:
    - script: phpunit --version
