language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0.2
env:
  - SYMFONY_VERSION=2.7.6
  - SYMFONY_VERSION=2.7.8
  - SYMFONY_VERSION=2.7.9
  - SYMFONY_VERSION=dev-master

script:
   - phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - script: phpunit --version
