<?php

namespace DocumentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentoActividadRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoActividadRepository extends EntityRepository
{
}
