#Aviso: la relación many to many todavía no se puede mostrar en el admin bundle
#referencia: https://github.com/javiereguiluz/EasyAdminBundle/issues/423
easy_admin:
    site_name: 'Learn-In Admin'
    entities:
        Usuario:
            class: UserBundle\Entity\Usuario
            list:
                fields: ['nombre','apellidos','username','email','cursos', 'enabled','lastLogin','roles']
            new:
                fields: ['nombre','apellidos',,'username','email','enabled','password','roles']
            edit:
                fields: ['nombre','apellidos',,'username','email','enabled','lastLogin','password','expiresAt','locked','expired','roles']
        Cursos:
            class: CursoBundle\Entity\Curso 
        Documentos:
            class: DocumentBundle\Entity\Documento
        Facultad:
            class: CursoBundle\Entity\Facultad
        Carrera:
            class: CursoBundle\Entity\Carrera
            class: CursoBundle\Entity\Periodo

