document_actividad:
    resource: "@DocumentBundle/Controller/ActividadController.php"
    type:     annotation

document_actividad:
    resource: "@DocumentBundle/Controller/ActividadController.php"
    type:     annotation

report:
    resource: "@ReportBundle/Resources/config/routing.php"
    prefix:   /

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

reporte:
    resource: "@ReportBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@CursoBundle/Controller/"
    type:     annotation

default:
    resource: "@UserBundle/Controller/"
    type:     annotation

document:
    resource: "@DocumentBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    #resource: "@CursoBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /adminEntity

