security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
            remember_me:
                secret:   "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
            logout:
                path: /logout
                target: /api/logout
                invalidate_session: true
            anonymous:    true
            access_denied_url: /contact/access/exception
            #access_denied_handler: kernel.listener.accessDenied
            #entry_point: kernel.listener.accessDenied
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/curso, roles: ROLE_CATEDRATICO }
        - { path: ^/carrera, roles: ROLE_ADMIN }
        - { path: ^/facultad, roles: ROLE_ADMIN }
        - { path: ^/adminEntity, role: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }



    role_hierarchy:
        ROLE_CATEDRATICO: ROLE_USER
        ROLE_ADMIN:       ROLE_CATEDRATICO
        ROLE_SUPER_ADMIN: ROLE_ADMIN
       
